### ISSUE TITLE
v0.2-beta

### ISSUE THREAD

**Issue by bossbuwi** [bossbuwi/existence#2]
### Next Release Targets

- [x]  Add capability to use a third party server for user authentication. Fixed by #6 
- [x] Complete the CRUD functions for the constellation ballad. Fixed by #6 
- [x] Add capability to delete users. Fixed by #6
- [x] Add capability to detect banned users. Fixed by #6 
- [x] ~~Add capability to recognize user roles system-wide.~~ This may be too large and needs its own release.
- [x] Password changing needs to be streamlined, just like how standard password changing on web sites are implemented. An old password and two instances of new passwords are needed. Fixed by #6 
- [x] ~~Handle user log out correctly using Spring Security.~~ Not possible due to the JWT implementation. It needs to be released on its own version.

### Next Release Dreams

- [x] ~~Complete the CRUD functions for the constellation sonata.~~ Won't be included.
- [x] ~~Complete the frontend part of the app.~~ Won't be included.

### Additional Changes

- Cleaned up and added comments on the liquibase changelogs for easier record reading and maintenance. Fixed by #3 
- Added new process to reset the default admin roles, in case they have been tampered with. This needs the master password for authorization. Fixed by #6 
- #4 
- #5 
- #10

**Comment by bossbuwi** [comment]
Documented under [v0.2beta](https://github.com/bossbuwi/existence/releases/tag/v0.2beta).
