### ISSUE TITLE
v1.0cassiopeia

### ISSUE THREAD

**Issue by bossbuwi** [bossbuwi/existence#68]
### Targets

- [ ] Search feature for Event entity. #69 
- [ ] Report creation and export to worksheet capability for Event entity.
- [x] Accept a worksheet upload for Event entity import.
- [x] Finish the **New System** interface on reality. #76 
- [x] Remove the authority restriction on creating systems and other entities. #76 
- [x] Create a switchable feature that controls if the Coblogs is enabled. #74 
- [x] Finish the Settings feature. #74 #77

**Comment by bossbuwi** [comment]
Closed by pull request #79
